version: '3.4'
services: 
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    restart: "always"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "test@123"
      MSSQL_PID: "Express"
    ports: 
      - "1433:1433"